FORM_TEMPLATES = {
    "cover_sheet": {
        "title_patterns": [
            r"\b(?:va\s+)?submission\s+cover\s+sheet\b",
            r"\bcommunity\s+care\s+submission\s+cover\s+sheet\b",
        ],
        "strong_patterns": [
            r"\bsubmission\s+cover\s+sheet\b",
            r"\bdocuments\s+included\b",
        ],
        "packet_level_patterns": [
            r"\b(?:va\s+)?submission\s+cover\s+sheet\b",
        ],
        "structure_signatures": [
            r"\bdocuments\s+included\b",
            r"\bdate\s+of\s+submission\b",
            r"\bprimary\s+diagnosis\s+code\b",
            r"\bsubmitting\s+office\b",
            r"\boffice\s+staff\s+name\b",
            r"\bdate\s+reviewed\b",
        ],
        "negative_patterns": [
            r"\btelehealth\s+consent\b",
            r"\bconsent\s+for\s+medical\s+care\s+and\s+treatment\b",
            r"\bletter\s+of\s+medical\s+necessity\b",
            r"\bconsultation\s+and\s+treatment\s+request\b",
            r"\bsingle\s+episode\s+of\s+care\b",
            r"\brequest\s+for\s+service\b",
        ],
        "anchor_groups": [
            ["submission cover sheet"],
            ["documents included", "check all"],
            ["date of submission", "primary diagnosis code"],
            ["submitting office", "office staff name", "date reviewed"],
            ["virtual consent form", "va form 10-10172", "clinical notes included", "letter of medical necessity"],
        ],
        "anchor_group_threshold": 2,
        "expected_fields": [
            "name",
            "dob",
            "ordering_provider",
            "facility",
            "clinic_name",
            "diagnosis",
            "signature_present",
        ],
    },
    "consent": {
        "title_patterns": [
            r"\btelehealth\s+virtual\s+consent\s+form\b",
            r"\bvirtual\s+consent\s+form\b",
            r"\btelehealth\s+consent\b",
        ],
        "strong_patterns": [
            r"\btelehealth\s+virtual\s+consent\s+form\b",
            r"\bvirtual\s+consent\s+form\b",
            r"\bconsent\s+for\s+medical\s+care\s+and\s+treatment\b",
            r"\btelehealth\s+consent\b",
        ],
        "packet_level_patterns": [
            r"\btelehealth\s+virtual\s+consent\s+form\b",
            r"\bvirtual\s+consent\s+form\b",
        ],
        "structure_signatures": [
            r"\bconsent\s+for\s+medical\s+care\s+and\s+treatment\b",
            r"\btelehealth\s+consent\b",
            r"\bappointment\s+confirmation\s+method\b",
            r"\bemergency\s+contact\b",
            r"\bpatient\s+signature\b",
            r"\bbenefits\s+and\s+risks\s+involved\s+with\s+telehealth\s+technology\b",
        ],
        "negative_patterns": [
            r"\bsubmission\s+cover\s+sheet\b",
            r"\bletter\s+of\s+medical\s+necessity\b",
            r"\bconsultation\s+and\s+treatment\s+request\b",
            r"\bsingle\s+episode\s+of\s+care\b",
            r"\brequest\s+for\s+service\b",
            r"\bencounter\s+date\b",
            r"\bchief\s+complaint\b",
            r"\bhistory\s+of\s+present\s+illness\b",
        ],
        "anchor_groups": [
            ["telehealth virtual consent form", "virtual consent form", "telehealth consent"],
            ["consent for medical care and treatment", "consent for care"],
            ["consent to participate in telehealth sessions", "benefits and risks involved with telehealth technology", "interactive video connection"],
            ["patient signature", "appointment confirmation method", "emergency contact"],
            ["full name", "date of birth", "home phone", "mobile phone"],
        ],
        "anchor_group_threshold": 2,
        "expected_fields": [
            "name",
            "dob",
            "signature_present",
        ],
    },
    "consult_request": {
        "title_patterns": [
            r"\bconsultation\s+and\s+treatment\s+request\b",
            r"\bconsult\s+and\s+treatment\s+request\b",
        ],
        "strong_patterns": [
            r"\bconsultation\s+and\s+treatment\s+request\b",
            r"\breason\s+for\s+consultation\b",
            r"\brequested\s+services\b",
            r"\bmedical\s+rationale\b",
        ],
        "packet_level_patterns": [
            r"\bconsultation\s+and\s+treatment\s+request\b",
        ],
        "structure_signatures": [
            r"\breason\s+for\s+consultation\b",
            r"\bdiagnoses\b",
            r"\bclinical\s+summary\b",
            r"\brequested\s+services\b",
            r"\bmedical\s+rationale\b",
            r"\bduration\s+and\s+scope\s+of\s+care\b",
            r"\bauthorization\s+is\s+requested\s+for\b",
        ],
        "negative_patterns": [
            r"\bletter\s+of\s+medical\s+necessity\b",
            r"\bsingle\s+episode\s+of\s+care\b",
            r"\btelehealth\s+consent\b",
            r"\bdocuments\s+included\b",
            r"\brequest\s+for\s+service\b",
        ],
        "anchor_groups": [
            ["consultation and treatment request", "consult and treatment request"],
            ["reason for consultation", "requested services"],
            ["medical rationale", "authorization is requested for"],
            ["duration and scope of care", "diagnostic confirmation and procedural planning"],
            ["referring va provider", "va claim number", "veteran name"],
        ],
        "anchor_group_threshold": 2,
        "expected_fields": [
            "name",
            "dob",
            "ordering_provider",
            "referring_provider",
            "authorization_number",
            "va_icn",
            "claim_number",
            "reason_for_request",
            "facility",
            "clinic_name",
            "location",
        ],
    },
    "seoc": {
        "title_patterns": [
            r"\bsingle\s+episode\s+of\s+care\b",
            r"\bseoc\b",
        ],
        "strong_patterns": [
            r"\bsingle\s+episode\s+of\s+care\b",
            r"\bscope\s+of\s+requested\s+episode\b",
            r"\bestimated\s+duration\s+of\s+episode\b",
        ],
        "packet_level_patterns": [
            r"\bsingle\s+episode\s+of\s+care\b",
            r"\bseoc\b",
        ],
        "structure_signatures": [
            r"\bepisode\s+diagnosis\b",
            r"\bscope\s+of\s+requested\s+episode\b",
            r"\bestimated\s+duration\s+of\s+episode\b",
            r"\bclinical\s+objective\b",
            r"\bcontinuity\s+of\s+care\b",
            r"\bprocedure-based\s+intervention\b",
        ],
        "negative_patterns": [
            r"\bletter\s+of\s+medical\s+necessity\b",
            r"\bconsultation\s+and\s+treatment\s+request\b",
            r"\btelehealth\s+consent\b",
            r"\bdocuments\s+included\b",
            r"\brequest\s+for\s+service\b",
        ],
        "anchor_groups": [
            ["single episode of care", "seoc request", "seoc"],
            ["scope of requested episode", "estimated duration of episode"],
            ["episode diagnosis", "clinical objective"],
            ["continuity of care", "procedure-based intervention", "separate evaluation and authorization"],
        ],
        "anchor_group_threshold": 2,
        "expected_fields": [
            "name",
            "dob",
            "facility",
            "clinic_name",
            "location",
            "authorization_number",
            "service_date_range",
            "diagnosis",
        ],
    },
    "lomn": {
        "title_patterns": [
            r"\bletter\s+of\s+medical\s+necessity\b",
            r"\bmedical\s+necessity\s+letter\b",
        ],
        "strong_patterns": [
            r"\bletter\s+of\s+medical\s+necessity\b",
            r"\bmedical\s+necessity\b",
            r"\bmedically\s+reasonable\s+and\s+necessary\b",
        ],
        "packet_level_patterns": [
            r"\bletter\s+of\s+medical\s+necessity\b",
        ],
        "structure_signatures": [
            r"\bto\s+whom\s+it\s+may\s+concern\b",
            r"\bclinical\s+summary\b",
            r"\bmedical\s+necessity\b",
            r"\bmedically\s+reasonable\s+and\s+necessary\b",
            r"\bwithout\s+appropriate\s+interventional\s+treatment\b",
            r"\bfailure\s+of\s+conservative\b",
        ],
        "negative_patterns": [
            r"\bsingle\s+episode\s+of\s+care\b",
            r"\bconsultation\s+and\s+treatment\s+request\b",
            r"\btelehealth\s+consent\b",
            r"\bdocuments\s+included\b",
            r"\brequest\s+for\s+service\b",
        ],
        "anchor_groups": [
            ["letter of medical necessity", "medical necessity letter"],
            ["to whom it may concern", "medical necessity"],
            ["clinical summary", "medical necessity"],
            ["medically reasonable and necessary", "without appropriate interventional treatment"],
            ["structured physical therapy", "activity modification", "home exercise program", "epidural steroid"],
        ],
        "anchor_group_threshold": 2,
        "expected_fields": [
            "name",
            "dob",
            "ordering_provider",
            "diagnosis",
            "reason_for_request",
            "facility",
            "signature_present",
        ],
    },
    "rfs": {
        "title_patterns": [
            r"\bcommunity\s+care\s+provider\b.*\brequest\s+for\s+service\b",
            r"\bva\s+form\s+10[\s\-]*10172\b",
            r"\b10[\s\-]*10172\b",
            r"\brequest\s+for\s+service(?:s)?\b",
        ],
        "strong_patterns": [
            r"\bva\s+form\s+10[\s\-]*10172\b",
            r"\brequest\s+for\s+service\b",
            r"\bva\s+authorization\s+number\b",
            r"\bdiagnosis\s+codes\s+\(icd-10\)\b",
        ],
        "packet_level_patterns": [
            r"\b(?:community\s+care\s+provider\s+\-\s+)?(?:medical\s+)?request\s+for\s+service(?:s)?\b",
            r"\b(?:va\s+form\s+)?10[\s\-]*10172\b",
        ],
        "structure_signatures": [
            r"\brequest\s+for\s+service\s+\(rfs\)\s+submission\s+requirements\b",
            r"\bcomplete\s+rfs\s+form\s+10[\s\-]*10172\b",
            r"\bsection\s+i:\s*veteran\s*&\s*ordering\s+provider\s+information\b",
            r"\bsection\s+ii:\s*type\s+of\s+care\s+request\b",
            r"\bdiagnosis\s+codes\s+\(icd-10\)\b",
            r"\breason\s+for\s+request\b",
            r"\bordering\s+provider\s+signature\b",
            r"\bva\s+authorization\s+number\b",
        ],
        "negative_patterns": [
            r"\bsubmission\s+cover\s+sheet\b",
            r"\bdocuments\s+included\b",
            r"\bconsultation\s+and\s+treatment\s+request\b",
            r"\bletter\s+of\s+medical\s+necessity\b",
            r"\btelehealth\s+consent\b",
        ],
        "anchor_groups": [
            ["va form 10-10172", "10-10172", "request for service"],
            ["community care provider", "section i", "veteran & ordering provider information"],
            ["va authorization number", "ordering provider office name & address", "ordering provider npi"],
            ["type of care request", "diagnosis codes (icd-10)", "reason for request"],
            ["ordering provider signature", "today's date", "submission requirements"],
        ],
        "anchor_group_threshold": 2,
        "expected_fields": [
            "name",
            "dob",
            "ordering_provider",
            "referring_provider",
            "authorization_number",
            "va_icn",
            "claim_number",
            "service_date_range",
            "facility",
            "clinic_name",
            "location",
        ],
    },
    "clinical_notes": {
        "title_patterns": [
            r"\bclinical\s+notes?\b",
            r"\bprogress\s+notes?\b",
            r"\bclinical\s+documentation\s+template\b",
        ],
        "strong_patterns": [
            r"\bclinical\s+documentation\s+template\b",
            r"\bhistory\s+of\s+present\s+illness\b",
            r"\bassessment(?:\s+and\s+plan|\s*/\s*plan)?\b",
            r"\bencounter\s+performed\s+and\s+documented\b",
        ],
        "packet_level_patterns": [
            r"\bclinical\s+documentation\s+template\b",
            r"\bclinical\s+notes?\b",
        ],
        "structure_signatures": [
            r"\bchief\s+complaint\b",
            r"\bhistory\s+of\s+present\s+illness\b",
            r"\bfunctional\s+impairment\b",
            r"\bconservative\s+therapy\s+history\b",
            r"\bimaging\s+findings\b",
            r"\bassessment(?:\s+and\s+plan|\s*/\s*plan)?\b",
            r"\btreatment\s+plan\b",
            r"\bphysical\s+exam\b",
            r"\bencounter\s+performed\s+and\s+documented\b",
        ],
        "negative_patterns": [
            r"\bsubmission\s+cover\s+sheet\b",
            r"\bconsent\s+for\s+medical\s+care\s+and\s+treatment\b",
            r"\bletter\s+of\s+medical\s+necessity\b",
            r"\bconsultation\s+and\s+treatment\s+request\b",
            r"\bsingle\s+episode\s+of\s+care\b",
            r"\brequest\s+for\s+service\b",
        ],
        "anchor_groups": [
            ["clinical documentation template", "clinical note", "clinical notes", "progress note"],
            ["chief complaint", "history of present illness"],
            ["functional impairment", "conservative therapy history", "imaging findings"],
            ["assessment", "treatment plan", "assessment and plan", "physical exam"],
            ["encounter performed and documented", "encounter reviewed & signed", "electronically signed"],
        ],
        "anchor_group_threshold": 2,
        "expected_fields": [
            "name",
            "dob",
            "provider",
            "ordering_provider",
            "referring_provider",
            "va_icn",
            "diagnosis",
            "symptom",
            "procedure",
            "icd_codes",
            "medications",
            "service_date_range",
            "facility",
            "clinic_name",
            "location",
            "signature_present",
        ],
    },
    "imaging_report": {
        "title_patterns": [
            r"\bmri\s+report\b",
            r"\blumbar\s+spine\s+mri\s+report\b",
            r"\bradiology\s+report\b",
            r"\bimaging\s+report\b",
        ],
        "strong_patterns": [
            r"\bmri\s+report\b",
            r"\blumbar\s+spine\s+mri\s+report\b",
            r"\bradiology\s+report\b",
            r"\bfindings\b",
            r"\bimpression\b",
        ],
        "packet_level_patterns": [
            r"\bmri\s+report\b",
            r"\bradiology\s+report\b",
        ],
        "structure_signatures": [
            r"\bstudy\s+date\b",
            r"\bexam\b",
            r"\bfindings\b",
            r"\bimpression\b",
            r"\bcomparison\b",
            r"\bclinical\s+indication\b",
        ],
        "negative_patterns": [
            r"\bsubmission\s+cover\s+sheet\b",
            r"\btelehealth\s+consent\b",
            r"\bconsultation\s+and\s+treatment\s+request\b",
            r"\bletter\s+of\s+medical\s+necessity\b",
            r"\bclinical\s+documentation\s+template\b",
        ],
        "anchor_groups": [
            ["mri report", "radiology report", "imaging report"],
            ["study date", "findings", "impression"],
            ["clinical indication", "comparison", "exam"],
        ],
        "anchor_group_threshold": 2,
        "expected_fields": [],
    },
    "conservative_care_summary": {
        "title_patterns": [
            r"\bconservative\s+care\s+summary\b",
            r"\bconservative\s+treatment\s+summary\b",
        ],
        "strong_patterns": [
            r"\bconservative\s+care\s+summary\b",
            r"\bconservative\s+treatment\s+summary\b",
        ],
        "packet_level_patterns": [
            r"\bconservative\s+care\s+summary\b",
            r"\bconservative\s+treatment\s+summary\b",
        ],
        "structure_signatures": [
            r"\bprior\s+conservative\s+therapy\s+documentation\b",
            r"\bstructured\s+physical\s+therapy\b",
            r"\bhome\s+exercise\s+program\b",
            r"\bactivity\s+modification\b",
            r"\boral\s+anti-?inflammatory\b",
            r"\bepidural\s+steroid\b",
            r"\btreatment\s+history\b",
        ],
        "negative_patterns": [
            r"\bletter\s+of\s+medical\s+necessity\b",
            r"\bclinical\s+documentation\s+template\b",
            r"\bconsultation\s+and\s+treatment\s+request\b",
            r"\brequest\s+for\s+service\b",
        ],
        "anchor_groups": [
            ["conservative care summary", "conservative treatment summary"],
            ["structured physical therapy", "home exercise program", "activity modification"],
            ["oral anti-inflammatory", "epidural steroid", "treatment history"],
        ],
        "anchor_group_threshold": 2,
        "expected_fields": [],
    },
}


SUPPORTED_DOCUMENT_TYPES = tuple(FORM_TEMPLATES.keys())
